### ISSUE TITLE
Practica de Hilos en Consola

### ISSUE THREAD

**Issue by IsaacCS1** [SistemasTecTlaxiaco/practica-de-hilos-IsaacCS1#2]
[PRACTICA_6.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-hilos-IsaacCS1/files/8520870/PRACTICA_6.pdf)

**Comment by IrvingFernand0** [comment]
Calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado....
